#lang planet neil/sicp

(define (make-account balance password)
  (define count 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (incorrect-password amount)
    (set! count (+ count 1))
    (if (= count 7)
        (call-the-cops))
    (string-append "Incorrect password. count = " (number->string count)))
  (define (call-the-cops)
    (set! count 0)
    (error "call-the-cops"))
  (define (dispatch p m)
    (if (not (eq? p password))
        incorrect-password
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m)))))
  dispatch)

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 40)
((acc 'some-other-password 'deposit) 1)
((acc 'some-other-password 'deposit) 2)
((acc 'some-other-password 'deposit) 3)
((acc 'some-other-password 'deposit) 4)
((acc 'some-other-password 'deposit) 5)
((acc 'some-other-password 'deposit) 6)
((acc 'some-other-password 'deposit) 7)
