#lang planet neil/sicp

(#%require (only racket include))
(include "./ch5-regsim.rkt")
(set! make-stack make-stack-with-monitor)

(include "./ch5-syntax.rkt")
(include "./ch5-eceval-support.rkt")

(define (lexical-address-lookup address env)
  (let ((frame-number (car address)) (displacement-number (cadr address)))
    (define (lookup-frame counter env)
      (if (eq? env the-empty-environment)
          (error "Unbound variable" address)
          (let ((frame (first-frame env)))
            (if (eq? counter frame-number)
                frame
                (lookup-frame (+ counter 1) (enclosing-environment env))))))
    (define (lookup-variable counter vars vals)
      (cond ((null? vars)
             (error "Unbound variable" address))
            ((eq? counter displacement-number)
             val)
            (else
             (lookup-variable (+ counter 1) (cdr vars) (cdr vals)))))
    (let ((frame (lookup-frame 0 env)))
      (let ((variable (lookup-variable 0 (frame-variables frame) (frame-values frame))))
        (if (eq? (car variable) '*unassigned*)
            (error "Unbound variable" address)
            (car variable))))))

(define (lexical-address-set! address val env)
  (let ((frame-number (car address)) (displacement-number (cadr address)))
    (define (lookup-frame counter env)
      (if (eq? env the-empty-environment)
          (error "Unbound variable" address)
          (let ((frame (first-frame env)))
            (if (eq? counter frame-number)
                frame
                (lookup-frame (+ counter 1) (enclosing-environment env))))))
    (define (lookup-variable counter vars vals)
      (cond ((null? vars)
             (error "Unbound variable" address))
            ((eq? counter displacement-number)
             val)
            (else
             (lookup-variable (+ counter 1) (cdr vars) (cdr vals)))))
    (let ((frame (lookup-frame 0 env)))
      (let ((variable (lookup-variable 0 (frame-variables frame) (frame-values frame))))
        (set-car! variable val)))))
